"""Init

Revision ID: 07c9b8433cc3
Revises: 963fd802bb86
Create Date: 2023-02-25 20:26:25.941344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c9b8433cc3'
down_revision = '963fd802bb86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
