"""Init

Revision ID: 156f868771a9
Revises: 7ea5ed3e49cb
Create Date: 2023-02-25 20:51:20.727222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156f868771a9'
down_revision = '7ea5ed3e49cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
