"""Init

Revision ID: 1d20ab8c2be2
Revises: 7e75be31a1f7
Create Date: 2023-02-27 00:36:32.326952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d20ab8c2be2'
down_revision = '7e75be31a1f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
