"""Init

Revision ID: 4ae2080d6f67
Revises: aa63b2fbbd4a
Create Date: 2023-02-25 06:09:54.231945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae2080d6f67'
down_revision = 'aa63b2fbbd4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
