"""Init

Revision ID: 76ee74dc3f3d
Revises: b64e6fa3bd17
Create Date: 2023-02-25 22:23:17.663119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ee74dc3f3d'
down_revision = 'b64e6fa3bd17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('grade', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'grade')
    # ### end Alembic commands ###
