"""Init

Revision ID: 7e16ded99dc2
Revises: 6e8ada34264e
Create Date: 2023-02-25 02:13:31.373075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e16ded99dc2'
down_revision = '6e8ada34264e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
