"""Init

Revision ID: 7e75be31a1f7
Revises: 76ee74dc3f3d
Create Date: 2023-02-27 00:33:46.861517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e75be31a1f7'
down_revision = '76ee74dc3f3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'date_of',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'date_of',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
