"""Init

Revision ID: 7ea5ed3e49cb
Revises: c24485ad4a77
Create Date: 2023-02-25 20:47:15.699889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea5ed3e49cb'
down_revision = 'c24485ad4a77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
