"""Init

Revision ID: c24485ad4a77
Revises: c00f1e85c215
Create Date: 2023-02-25 20:32:27.958740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24485ad4a77'
down_revision = 'c00f1e85c215'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
