"""Init

Revision ID: e220247497ea
Revises: 7e16ded99dc2
Create Date: 2023-02-25 04:19:05.613978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e220247497ea'
down_revision = '7e16ded99dc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
