"""Init

Revision ID: fbadab663a06
Revises: cdd68be8ea99
Create Date: 2023-02-27 01:32:32.639152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbadab663a06'
down_revision = 'cdd68be8ea99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
